name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/bose_unofficial_api/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/bose_unofficial_api"
          zip bose_unofficial_api.zip -r ./

      - name: "Upload the ZIP file to the release"
        # Pinning the version as this is not a trusted action (github's)
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: ${{ github.workspace }}/custom_components/bose_unofficial_api/bose_unofficial_api.zip
